# Generated by Django 4.0.5 on 2022-07-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
