# Generated by Django 4.0.5 on 2022-07-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review_ratio',
            field=models.IntegerField(default=0),
        ),
    ]
