# Generated by Django 4.0.5 on 2022-07-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_review_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='review_ratio',
            new_name='project_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
