# Generated by Django 4.0.5 on 2022-07-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_review_ratio_profile_project_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vote_count',
            new_name='review_count',
        ),
    ]
